# Scenario: Standardizing "Messy" Clinical Units

In [4]:
import pandas as pd
import sqlite3
#creating a data with mixed Temperature units
temp_data = {
    "reading_id": [1, 2, 3, 4, 5, 6],
    "patient_id": ["P-A", "P-B", "P-C", "P-D", "P-E", "P-F"],
    "temp_value": [37.2, 98.6, 38.5, 101.2, 36.8, 99.5],
    "unit": ["C", "F", "C", "F", "C", "F"]
}
# adding data to the DataFrame
df_temp_data = pd.DataFrame(temp_data)
# connecting the sql
connt = sqlite3.connect(":memory:")
# saving dataset to sql temp memory
df_temp_data.to_sql("tempo_data", connt, index = False, if_exists = "replace")
# function to run the query
def run_query(query):
    return pd.read_sql(query, connt)
print("******************************** tempo dataset has been created!!! ******************")
print()

******************************** tempo dataset has been created!!! ******************

# Identify the "Outliers"

In [6]:
# query for all dataset for a quick look
all_data = "SELECT * FROM tempo_data "
print("************************************ all data for review *************************")
display(run_query(all_data))
# query to find all patient records where the unit is 'F'.
fahrenheits = """
SELECT patient_id, temp_value, unit FROM tempo_data 
WHERE unit = 'F'

"""
print("************************************ fahrenheit values ***************************** ")
display(run_query(fahrenheits))
print()

************************************ all data for review *************************

   reading_id patient_id  temp_value unit
0           1        P-A        37.2    C
1           2        P-B        98.6    F
2           3        P-C        38.5    C
3           4        P-D       101.2    F
4           5        P-E        36.8    C
5           6        P-F        99.5    F

************************************ fahrenheit values *****************************

  patient_id  temp_value unit
0        P-B        98.6    F
1        P-D       101.2    F
2        P-F        99.5    F

# The "Translation" Query (Math in SQL)

In [7]:
# query that returns the patient_id and a new calculated column called temp_celsius
f_to_c = """
SELECT patient_id
    CASE
        WHEN unit_id = 'F' THEN (temp_value - 32) * 5 / 9
        ELSE temp_value
    END AS temp_celsius
FROM tempo_data
"""
print("*************************************** all celsius dataset***************************")
display(run_query(f_to_c))

*************************************** all celsius dataset***************************

DatabaseError: Execution failed on sql '
SELECT patient_id
    CASE
        WHEN unit_id = 'F' THEN (temp_value - 32) * 5 / 9
        ELSE temp_value
    END AS temp_celsius
FROM tempo_data
': near "CASE": syntax error